version: "3.9"

services:
  db:
    container_name: "postgres_db"
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: admin
    volumes:
      - /pgdata:/var/lib/postgresql/data
  server:
    image: node:14
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: npx ts-node-dev --respawn src/server.ts
    env_file: .env.local
